---

foo: 123

bar:
  bax: [1, 2, 3, 4.5]
  bazz: 24
  more:
    bla: 'hello'
    blabla: ${foo} #value of foo will be taken here


my_func:
  _target_: toy.function_test
  x: 123
  y: 321

#calling the func at later part of the code

my_partial_func:
  _target_: toy.function_test
  _partial_: true
  x: 123

my_object:
  _target_: toy.MyClass
  x: 32

my_complex_object:
  _target_: toy.MyComplexClass
  _recursive_: false #setting false will not instantiate the my_object its required to instantitate sometime later
  my_object:
    _target_: toy.MyClass
    x: ${bar.bazz}


defaults:
  - toy_model: resnet18  # fetches the default model as resnet18 but to fetch other model, specify toy_model=modelname while running the command